/**
 * Created by digvita on 2017/7/12.
 */
app.config(["$routeProvider",function ($routeProvider) {
    $routeProvider
    //.when('/page1',{templateUrl:'tpl/page1.html',controller:'page1C'})
    //     .when('/page2', {templateUrl: 'view/page2.html', controller: 'page2C'})
    //     .when('/page3', {templateUrl: 'view/page3.html', controller: 'page3C'})
    //     .when('/page4', {templateUrl: 'view/page4.html', controller: 'page4C'})
    //     //.when('/page5',{templateUrl:'tpl/page5.html',controller:'page5C'})
    //     .when('/page6', {templateUrl: 'view/page6.html', controller: 'page6C'})
    //     .when('/page7', {templateUrl: 'view/page7.html', controller: 'page7C'})
    //     .when('/page8', {templateUrl: 'view/page8.html', controller: 'page8C'})
    //     .when('/page9', {templateUrl: 'view/page9.html', controller: 'page9C'})
    //     .when('/page10', {templateUrl: 'view/page10.html', controller: 'page10C'})
    //     .when('/page11', {templateUrl: 'view/page11.html', controller: 'page11C'})
    //     .when('/page12', {templateUrl: 'view/page12.html', controller: 'page12C'})
    //     .when('/page13', {templateUrl: 'view/page13.html', controller: 'page13C'})
    //     .when('/page14', {templateUrl: 'view/page14.html', controller: 'page14C'})
    //     .when('/page15', {templateUrl: 'view/page15.html', controller: 'page15C'})
    //     .when('/page16', {templateUrl: 'view/page16.html', controller: 'page16C'})
    //     .when('/page17', {templateUrl: 'view/page17.html', controller: 'page17C'})
    //     .when('/page18', {templateUrl: 'view/page18.html', controller: 'page18C'})
    //     .when('/page19', {templateUrl: 'view/page19.html', controller: 'page19C'})
    //     .when('/page20', {templateUrl: 'view/page20.html', controller: 'page20C'})
    //     .when('/page21', {templateUrl: 'view/page21.html', controller: 'page21C'})
    //     .when('/page22', {templateUrl: 'view/page22.html', controller: 'page22C'})
    //     .when('/page23', {templateUrl: 'view/page23.html', controller: 'page23C'})
    //     .when('/page24', {templateUrl: 'view/page24.html', controller: 'page24C'})
    //     .when('/page25', {templateUrl: 'view/page25.html', controller: 'page25C'})
    //     .when('/page26', {templateUrl: 'view/page26.html', controller: 'page26C'})
    //     .when('/page27', {templateUrl: 'view/page27.html', controller: 'page27C'})
    //     .when('/page28', {templateUrl: 'view/page28.html', controller: 'page28C'})
    //     .when('/page29', {templateUrl: 'view/page29.html', controller: 'page29C'})
    //     .when('/page30', {templateUrl: 'view/page30.html', controller: 'page30C'})
    //     .when('/page31', {templateUrl: 'view/page31.html', controller: 'page31C'})
    //     .when('/page32', {templateUrl: 'view/page32.html', controller: 'page32C'})
    //     .when('/page33', {templateUrl: 'view/page33.html', controller: 'page33C'})
        .when('/page34', {templateUrl: 'view/page34.html', controller: 'page34C'})
        .when('/page35', {templateUrl: 'view/page35.html', controller: 'page35C'})
        .when('/page36', {templateUrl: 'view/page36.html', controller: 'page36C'})
        .when('/page37', {templateUrl: 'view/page37.html', controller: 'page37C'})
        .when('/page38', {templateUrl: 'view/page38.html', controller: 'page38C'})
        .when('/page39', {templateUrl: 'view/page39.html', controller: 'page39C'})
        .when('/login', {templateUrl: 'view/login.html', controller: 'loginC'})
        .otherwise({redirectTo: '/page34'});
}]);